name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Backend Dependencies
      run: |
        cd server
        npm ci --prefix ./server

    - name: Build Backend
      run: |
        cd server
        npm run build --if-present --prefix ./server

    - name: Install Frontend Dependencies
      run: |
        cd client
        npm ci --prefix ./client

    - name: Build Frontend
      run: |
        cd client
        npm run build --if-present --prefix ./client
